config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'rooms#index'
  resources :users, only: [:show, :edit, :update]
  resources :roles, only: [:create]
  resources :rooms, only: [:create, :show, :update, :destroy], param: :token do
    resources :characters, only: [:create, :update]
    resources :secrets, only: [:create, :update]
    resources :open_secrets, only: [:update]
    get 'open_secrets/:id', to: 'open_secrets#unveiled'
    resources :last_resorts, only: [:create, :update]
    resources :open_last_resorts, only: [:update]
    get 'open_last_resorts/:id', to: 'open_last_resorts#unveiled'
    resources :conditions, only: [:create, :destroy]
    resources :feelings, only: [:create, :destroy]
  end
  get 'rooms/session_logs/:room_token/new', to: 'session_logs#new'
  resources :session_logs, only: [:create, :edit, :update, :destroy]
end

app/models/feeling.rb
class Feeling < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :feel

  belongs_to :character

  with_options presence: true do
    validates :feeling_to
    validates :feel_id, numericality: { other_than: 1 }
  end
end

app/controllers/feelings_controller.rb
class FeelingsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    @feeling = Feeling.new(feeling_params)
    respond_to do |format|
      if @feeling.save
        @num = Character.find(@feeling.character_id).pc_number
        @room = Room.find_by(token: params[:room_token])
        format.js { render 'add_feeling' }
      else
        flash[:feeling_info] = { feel_id: @feeling.feel_id, feeling_to: @feeling.feeling_to }
        flash[:error] = @feeling.errors.full_messages
        flash[:num] = params[:feeling][:pc_number].to_i
        flash[:match] = "feeling#{flash[:num]}"
        flash[:error_msg] = "PC#{flash[:num]}の感情を更新できませんでした。再度選択をお願いします。"
        format.js { render 'shared/errors' }
      end
      format.html { redirect_to room_path(token: params[:room_token]) }
    end
  end

  def destroy
    @feeling = Feeling.find(params[:id])
    @feeling.destroy
    respond_to do |format|
      format.html { redirect_to room_path(token: params[:room_token]) }
      format.js { render 'destroy' }
    end
  end

  private

  def feeling_params
    params.require(:feeling).permit(:feel_id, :feeling_to, :character_id)
  end
end

app/helpers/feelings_helper.rb
module FeelingsHelper
end

app/views/feelings/_delete_feeling.html.erb
<div class="del-list", id ="del-fe-<%=fe.id%>">
  <div class="feeling_contents">
    <div><%= fe.feel.name %></div>
    <div> → <%= fe.feeling_to %></div>
  </div>
  <div class="del_btn">
    <%= link_to "× 削除", room_feeling_path(room_token: @room.token, id: fe.id), method: :delete, remote: true %>
  </div>
</div>

app/views/feelings/_feeling_form.html.erb
<div class="wrap-char-form" id="add-feeling<%= num %>">
  <div class="form-background"></div>
  <div class="condition-feeling-form">
    <%= form_with model: @feeling, url: room_feelings_path(room_token: token), method: :post do |f| %>
      <div class="form-title">
          感情情報入力
        </div>
      <div class="form-contents">
        <% if flash[:error] && flash[:match] == "feeling#{num}" %>
          <div class="error-msg">
            <ul>
              <% flash[:error].each do |message| %>
                <% case message %>
                <% when "Feeling to can't be blank" %>
                  <li>PCを選択してください。</li>
                <% when "Feel must be other than 1" %>
                  <li>感情を選択してください。</li>
                <% end %>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="field">
          <%= f.label "感情" %><span class="required-items"> 必須</span><br />
          <%= f.collection_select(:feel_id, Feel.all, :id, :name, {}, {class: "select_box", id: "afefe-#{num}"}) %>
        </div>
        <div class="arrow-shape">↓</div><br />
        <div class="field">
          <%= f.label "誰に（感情を向けるPCを選択）" %><span class="required-items"> 必須</span><br />
          <% char_names = [] %>
          <% @characters.each do |char| %>
                <% if char != selected_char %>
                  <% char_names << char.character_name %>
                <% end %>
              <% end %>
          <%= f.select :feeling_to, char_names, {}, {class: "select_box", id: "afefet-#{num}"}%>
        </div>
        <%= f.hidden_field :character_id, value: selected_char.id, id: "afeci-#{num}" %>
        <%= f.hidden_field :pc_number, value: num, id: "afepn-#{num}" %>
        <button class="add-btn">
          <%= f.submit "追加" %>
        </button>
      </div>
      <div class="form-title">
        感情情報削除
      </div>
      <div class="form-contents">
        <% @feelings.each do |fe| %>
          <% if fe.character_id == selected_char.id %>
            <%= render 'feelings/delete_feeling', fe: fe %>
          <% end %>
        <% end %>
      <div id="del-feeling<%=num%>"></div>
      </div>
    <% end %>
  </div>
</div>

app/views/feelings/_show_feeling.html.erb
<div class="status_over_frame", data-target="feeling-info<%= num %>">
  <div class="status_name">
    感情
  </div>
  <div class="feeling_bubble", id="feeling-info<%= num %>">
    <div class="char-lower-display">
      <button class="add-charinfo-btn modal_form", data-target="add-feeling<%= num %>">
        追加/削除
      </button>
      <%= render "feelings/feeling_form", num: num, token: @room.token, selected_char: selected_char %>
      <% @feelings.each do |fe| %>
        <% if fe.character_id == selected_char.id %>
          <div class="bubble-list", id="fe-<%=fe.id%>">
            <div class="feeling_contents">
              <div><%= fe.feel.name %></div>
              <div> → <%= fe.feeling_to %></div>
            </div>
          </div>
        <% end %>
      <% end %>
      <div id="feelings-<%=num%>"></div>
    </div>
  </div>
</div>

app/views/feelings/add_feeling.js.erb
$("#feelings-<%=@num%>").append(
  "<div class='bubble-list'><div class='feeling_contents'><div><%= @feeling.feel.name %></div><div> → <%= @feeling.feeling_to %></div></div></div>"
  );
  $("#afefe-<%=@pc_num%>").val(['1']);
  $("#del-feeling<%=@num%>").append("<%= j(render 'feelings/delete_feeling', fe: @feeling) %>");
  $('.js-message-errors').empty();

app/views/feelings/destroy.js.erb
$("#del-fe-<%=@feeling.id%>").replaceWith('<div></div>');
$("#fe-<%=@feeling.id%>").replaceWith('<div></div>');