config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'rooms#index'
  resources :users, only: [:show, :edit, :update]
  resources :roles, only: [:create]
  resources :rooms, only: [:create, :show, :update, :destroy], param: :token do
    resources :characters, only: [:create, :update]
    resources :secrets, only: [:create, :update]
    resources :open_secrets, only: [:update]
    get 'open_secrets/:id', to: 'open_secrets#unveiled'
    resources :last_resorts, only: [:create, :update]
    resources :open_last_resorts, only: [:update]
    get 'open_last_resorts/:id', to: 'open_last_resorts#unveiled'
    resources :conditions, only: [:create, :destroy]
    resources :feelings, only: [:create, :destroy]
  end
  get 'rooms/session_logs/:room_token/new', to: 'session_logs#new'
  resources :session_logs, only: [:create, :edit, :update, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  validates :name, presence: true
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates :password, format: { with: PASSWORD_REGEX }, on: :create

  has_many :rooms
  has_many :roles
  has_many :session_logs, dependent: :destroy

  def self.guest
    user = User.where('email LIKE(?)', '%@shinobininja.com').order(:current_sign_in_at).first
    if user.nil?
      6.times do |num|
        User.create(name: "guest#{num + 1}", email: "guest#{num + 1}@shinobininja.com", password: "#{SecureRandom.alphanumeric(10)}2b")
      end
      User.find_by(name: 'guest1')
    else
      user
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update]

  def show
    @session_logs = SessionLog.where(user_id: current_user.id)
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render 'shared/header' %>

<div class="outer-form-wrap">
  <div class="form-wrap">
    <div class="form-title">
      ユーザー情報変更
    </div>
    <div class="form-contents">
      <%= form_with model: current_user, local: true do |f| %>

        <%= render 'shared/errors_messages', model: f.object %>
        
        <div class="field">
          <label>ユーザー名</label><span class="required-items"> 必須</span><br />
          <%= f.text_field :name, placeholder: "ユーザー名を入力", value: current_user.name, class: "text_box" %>
        </div>
        <div class="field">
          <label>メールアドレス</label><span class="required-items"> 必須</span><br />
          <%= f.email_field :email, placeholder: "メールアドレスを入力", value: current_user.email, class: "text_box" %>
        </div><br />
        <div>
          <%= f.submit "情報変更", class: "room-btn" %>
        </div><br />
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'shared/header' %>

<div class="outer-form-wrap">
  <div class="upper-user-info">
    <div class="user-info-wrap">
      <div class="form-title">
        ユーザー情報
      </div><br />
      <div class="user-info-title">ユーザー名</div>
      <div class="user_info">
        <%= current_user.name %>
      </div><br>
      <div class="user-info-title">メールアドレス</div>
      <div class="user_info">
        <%= current_user.email %>
      </div>
      <div class="change-user-btn"><%= link_to 'ユーザー情報変更', edit_user_path(current_user.id) %></div>
    </div><br />

    <div class="user-room-wrap">
      <div class="form-title">
        ルーム情報
      </div>
      <div class="form-contents">
        <% user_rooms = Room.where(user_id: current_user.id) %>
        ルーム名をクリックすると入室できます。<br /><br /><br />
        <% user_rooms.each do |room| %>
          <div class="room-link">
            <%= link_to room.room_name, room_path(token: room.token) %>
            <%# <div class="enter_room_btn">入室</div> %>
          </div>
        <% end %>
      </div>
      <br />
    </div>
  </div><br />

  <div class="form-wrap">
    <div class="form-title">
      セッション履歴
    </div>
    <div class="session-log-list">
      <% unless @session_logs[0].nil? %>
        <% @session_logs.each do |s| %>
          <div class="session-log">
            <div class="session-log-info">表題</div>
            <%= s.title %><br /><br />
            <div class="session-log-info">履歴作成日</div>
            <%= s.created_at.strftime("%Y年%m月%d日") %>
            <div class="session-log-link">
              <div><%= link_to '編集', edit_session_log_path(s.id), class: "log-link" %></div>
              <div><%= link_to '削除', session_log_path(s.id), method: :delete, class: "log-link" %></div>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="no-session-log">セッション履歴がまだありません。</div>
      <% end %>
    </div>
  </div>
</div>