config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'rooms#index'
  resources :users, only: [:show, :edit, :update]
  resources :roles, only: [:create]
  resources :rooms, only: [:create, :show, :update, :destroy], param: :token do
    resources :characters, only: [:create, :update]
    resources :secrets, only: [:create, :update]
    resources :open_secrets, only: [:update]
    get 'open_secrets/:id', to: 'open_secrets#unveiled'
    resources :last_resorts, only: [:create, :update]
    resources :open_last_resorts, only: [:update]
    get 'open_last_resorts/:id', to: 'open_last_resorts#unveiled'
    resources :conditions, only: [:create, :destroy]
    resources :feelings, only: [:create, :destroy]
  end
  get 'rooms/session_logs/:room_token/new', to: 'session_logs#new'
  resources :session_logs, only: [:create, :edit, :update, :destroy]
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :room
  has_many :secret, dependent: :destroy
  has_many :last_resort, dependent: :destroy
  has_many :feelings, dependent: :destroy
  has_many :conditions, dependent: :destroy

  with_options presence: true do
    validates :character_name
    validates :pc_number
  end
end

app/models/character_info.rb
class CharacterInfo
  include ActiveModel::Model
  attr_accessor :character_name, :pc_number, :secret_n, :secret, :last_resort_n, :last_resort

  with_options presence: true do
    validates :character_name
    validates :pc_number
    validates :secret_n
    validates :secret
    validates :last_resort_n
    validates :last_resort
  end

  def save(room)
    character = Character.create(character_name: character_name, pc_number: pc_number, room_id: room.id)
    open_sec = Secret.create(secret_n: secret_n, secret: secret, character_id: character.id)
    open_lr = LastResort.create(last_resort_n: last_resort_n, last_resort: last_resort, character_id: character.id)
    room.player_number.times do |n|
      if character.pc_number != n + 1
        OpenSecret.create(secret_unveil_to: n + 1, unveiled_id: 1, secret_id: open_sec.id)
        OpenLastResort.create(lr_unveil_to: n + 1, unveiled_id: 1, last_resort_id: open_lr.id)
      end
    end
  end
end

app/models/condition.rb
class Condition < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :state

  belongs_to :character

  validates :state_id, numericality: { other_than: 1 }
end

app/models/enter_room.rb
class EnterRoom
  include ActiveModel::Model
  attr_accessor :role, :token, :password, :user_id

  with_options presence: true do
    validates :role, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 8 }
    validates :token
    validates :password, length: { minimum: 4 }
  end

  def save(room)
    Role.create(role: role, user_id: user_id, room_id: room.id)
  end
end

app/models/feel.rb
class Feel < ActiveHash::Base
  self.data = [
    { id: 1, name: '感情を選択' },
    { id: 2, name: '共感(プラス)' },
    { id: 3, name: '不信(マイナス)' },
    { id: 4, name: '友情(プラス)' },
    { id: 5, name: '怒り(マイナス)' },
    { id: 6, name: '愛情(プラス)' },
    { id: 7, name: '妬み(マイナス)' },
    { id: 8, name: '忠誠(プラス)' },
    { id: 9, name: '侮蔑(マイナス)' },
    { id: 10, name: '憧憬(プラス)' },
    { id: 11, name: '劣等感(マイナス)' },
    { id: 12, name: '狂信(プラス)' },
    { id: 13, name: '殺意(マイナス)' }
  ]

  include ActiveHash::Associations
  has_many :feelings
end

app/models/feeling.rb
class Feeling < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :feel

  belongs_to :character

  with_options presence: true do
    validates :feeling_to
    validates :feel_id, numericality: { other_than: 1 }
  end
end

app/models/last_resort.rb
class LastResort < ApplicationRecord
  with_options presence: true do
    validates :last_resort_n
    validates :last_resort
  end

  belongs_to :character
  has_many :open_last_resorts, dependent: :destroy

  def self.create_open_lrs(room, lr_id, character)
    room.times do |n|
      OpenLastResort.create(lr_unveil_to: n + 1, unveiled_id: 1, last_resort_id: lr_id) if character.pc_number != n + 1
    end
  end
end

app/models/open_secret.rb
class OpenSecret < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :unveiled

  with_options presence: true do
    validates :secret_unveil_to
    validates :unveiled_id, inclusion: { in: [1, 2] }
  end

  belongs_to :secret
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
require 'securerandom'

class Room < ApplicationRecord
  before_create :create_token

  with_options presence: true do
    validates :room_name
    validates :player_number, numericality: { greater_than_or_equal_to: 2, less_than_or_equal_to: 8 }
  end
  # validates :password, length: { minimum: 4 }
  belongs_to :user
  has_many :characters, dependent: :destroy
  has_many :roles, dependent: :destroy
  has_secure_password

  def self.gm_role(room)
    Role.create(role: 200, user_id: room.user_id, room_id: room.id)
  end

  private

  def create_token
    self.token = SecureRandom.urlsafe_base64
  end
end

app/models/secret.rb
class Secret < ApplicationRecord
  with_options presence: true do
    validates :secret_n
    validates :secret
  end

  belongs_to :character
  has_many :open_secrets, dependent: :destroy

  def self.create_open_secrets(room, secret_id, character)
    room.times do |n|
      OpenSecret.create(secret_unveil_to: n + 1, unveiled_id: 1, secret_id: secret_id) if character.pc_number != n + 1
    end
  end
end

app/models/session_log.rb
class SessionLog < ApplicationRecord
  with_options presence: true do
    validates :title
    validates :log
  end
  belongs_to :user
end

app/models/state.rb
class State < ActiveHash::Base
  self.data = [
    { id: 1, name: '変調を選択' },
    { id: 2, name: '故障' },
    { id: 3, name: 'マヒ' },
    { id: 4, name: '重傷' },
    { id: 5, name: '行方不明' },
    { id: 6, name: '忘却' },
    { id: 7, name: '呪い' },
    { id: 8, name: '催眠' },
    { id: 9, name: '火達磨' },
    { id: 10, name: '猛毒' },
    { id: 11, name: '飢餓' },
    { id: 12, name: '残刃' },
    { id: 13, name: '野望' }
  ]

  include ActiveHash::Associations
  has_many :conditions
end

app/models/unveiled.rb
class Unveiled < ActiveHash::Base
  self.data = [
    { id: 1, name: '非公開' },
    { id: 2, name: '公開' }
  ]

  include ActiveHash::Associations
  has_many :open_secrets
  has_many :open_last_resorts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  validates :name, presence: true
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates :password, format: { with: PASSWORD_REGEX }, on: :create

  has_many :rooms
  has_many :roles
  has_many :session_logs, dependent: :destroy

  def self.guest
    user = User.where('email LIKE(?)', '%@shinobininja.com').order(:current_sign_in_at).first
    if user.nil?
      6.times do |num|
        User.create(name: "guest#{num + 1}", email: "guest#{num + 1}@shinobininja.com", password: "#{SecureRandom.alphanumeric(10)}2b")
      end
      User.find_by(name: 'guest1')
    else
      user
    end
  end
end

app/helpers/feelings_helper.rb
module FeelingsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_errors_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<%# CSS...assets/stylesheets/shared/header.css %>

<header>
  <div class="main-left-header">
      <%= link_to image_tag("title.png", class: "app-title"), root_path %>
  </div>
  <div class="main-right-header">
    <ul class="nav">
      <% if user_signed_in? %>
        <div class="user-name">
          <% if current_user.name == '' %>
            <li><%= link_to 'マイページへ戻る', user_path(current_user.id) %></li>
          <% else %>
            <li><%= link_to current_user.name, user_path(current_user.id) %></li>
          <% end %>
        </div>
        <li><%= link_to image_tag("logout_button.png", class: "logout"), destroy_user_session_path, method: :delete %></li>
      <% else%>
        <li><%= link_to image_tag("guest_login_button.png", class: "guest_login"), users_guest_sign_in_path, method: :post %></li>
        <li><%= link_to image_tag("login_button.png", class: "login"), new_user_session_path %></li>
        <li><%= link_to image_tag("signup_button.png", class: "sign-in"), new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second_header.html.erb
<%# セッションルームのヘッダー %>

<header>
  <div class="main-left-2header">
    <%= link_to image_tag("title.png", class: "app-title"), root_path %>
      <div class="room-name">部屋名<br />
        <button data-target="edit-room-name", class="room_name_btn modal_form"><%= @room.room_name %></button>
        <% if @role == 200 %>
          <%= render "rooms/room_name", room: @room %>
        <% end %>
      </div>
  </div>

  <div class="main-right-header">
    <ul class="nav">
      <% if @role == 200 %>
        <div class="create_playlog">
          <li><%= link_to '履歴作成', "/rooms/session_logs/#{params[:token]}/new" %></li>
        </div>
        <li><%= link_to image_tag("delete_room.png", class: "delete_room"), room_path, method: :delete,
        alt: "Delete_room", data: { confirm: "本当に部屋を削除してもよろしいですか？" } %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/errors.js.erb
<% if @char %>
  <% error = @char %>
<% elsif @add_secret %>
  <% error = @add_secret %>
<% elsif @edit_secret %>
  <% error = @edit_secret %>
<% elsif @add_last_resort %>
  <% error = @add_last_resort %>
<% elsif @edit_last_resort %>
  <% error = @edit_last_resort %>
<% elsif @condition %>
  <% error = @condition %>
<% elsif @feeling %>
  <% error = @feeling %>
<% elsif @room_name %>
  <% error = @room_name %>
<% end %>

$('.js-message-errors').replaceWith(
  "<%= j(render 'layouts/validation_errors',instance: error) %>"
);
$('.wrap-char-form').fadeOut(200);