config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'rooms#index'
  resources :users, only: [:show, :edit, :update]
  resources :roles, only: [:create]
  resources :rooms, only: [:create, :show, :update, :destroy], param: :token do
    resources :characters, only: [:create, :update]
    resources :secrets, only: [:create, :update]
    resources :open_secrets, only: [:update]
    get 'open_secrets/:id', to: 'open_secrets#unveiled'
    resources :last_resorts, only: [:create, :update]
    resources :open_last_resorts, only: [:update]
    get 'open_last_resorts/:id', to: 'open_last_resorts#unveiled'
    resources :conditions, only: [:create, :destroy]
    resources :feelings, only: [:create, :destroy]
  end
  get 'rooms/session_logs/:room_token/new', to: 'session_logs#new'
  resources :session_logs, only: [:create, :edit, :update, :destroy]
end

app/models/secret.rb
class Secret < ApplicationRecord
  with_options presence: true do
    validates :secret_n
    validates :secret
  end

  belongs_to :character
  has_many :open_secrets, dependent: :destroy

  def self.create_open_secrets(room, secret_id, character)
    room.times do |n|
      OpenSecret.create(secret_unveil_to: n + 1, unveiled_id: 1, secret_id: secret_id) if character.pc_number != n + 1
    end
  end
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :update]

  def create
    @add_secret = Secret.new(secret_params)
    respond_to do |format|
      if @add_secret.save
        character = Character.find(@add_secret.character_id)
        @room = Room.find_by(token: params[:room_token])
        Secret.create_open_secrets(@room.player_number, @add_secret.id, character)
        definition_create(character)
        format.js { render 'secrets/add_secret' }
      else
        error_message(params[:secret][:pc_number], @add_secret)
        format.js { render 'shared/errors' }
      end
      format.html { redirect_to room_path(token: params[:room_token]) }
    end
  end

  def update
    @edit_secret = Secret.find(params[:id])
    respond_to do |format|
      if @edit_secret.update(secret_params)
        @pc_num = Character.find(@edit_secret.character_id).pc_number
        format.js { render 'secrets/edit_secret' }
      else
        error_message(params[:secret][:pc_number], @edit_secret)
        format.js { render 'shared/errors' }
      end
      format.html { redirect_to room_path(token: params[:room_token]) }
    end
  end

  private

  def secret_params
    params.require(:secret).permit(:secret_n, :secret, :character_id)
  end

  def definition_create(character)
    @open_secrets = OpenSecret.where(secret_id: @add_secret.id)
    @role = Role.find_by(user_id: current_user.id, room_id: @room.id).role
    @secret = { num: character.pc_number, selected_char: character }
    @characters = Character.where(room_id: @room.id)
  end

  def error_message(num, input)
    flash[:error] = input.errors.full_messages
    flash[:num] = num.to_i
    flash[:match] = "secret#{flash[:num]}"
    flash[:error_msg] = "PC#{flash[:num]}の秘密を更新できませんでした。再度入力をお願いします。"
  end
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/views/secrets/_edit_secret.html.erb
<div class="wrap-char-form" id="edit-secret<%= num %>-<%= s.secret_n %>">
  <div class="form-background"></div>
  <div class="condition-feeling-form">
    <% @edit_secret = s %>
    <%= form_with model: @edit_secret, url: room_secret_path(id: s.id, room_token: token), method: :patch do |f| %>
      <div class="form-title">
        秘密<%=s.secret_n%>の編集
      </div>
      <div class="form-contents">
        <% if flash[:error] && flash[:match] == "secret#{num}" %>
          <div class="error-msg">
            <ul>
              <li><%= "秘密を入力してください。" %></li>
            </ul>
          </div>
        <% end %>
        <div class="field">
          <label for="esl-<%=num%>-<%=s.secret_n%>">秘密</label><span class="required-items"> 必須</span><br />
          <%= f.text_area :secret, placeholder: "秘密を入力", value: s.secret, class: "long_text_box", id: "esl-#{num}-#{s.secret_n}" %>
        </div>
        <%= f.hidden_field :character_id, value: selected_char.id, id: "e-sci-#{num}-#{s.secret_n}" %>
        <%= f.hidden_field :pc_number, value: num, id: "e-spn-#{num}-#{s.secret_n}" %>
        <%= f.hidden_field :secret_n, value: s.secret_n, id: "e-sn-#{num}-#{s.secret_n}" %>
      </div>
      <button class="add-btn">
        <%= f.submit "編集" %>
      </button>
    <% end %>

      <div class="form-title">
        公開・非公開の設定
      </div>
      <div class="form-contents">
        <div class="field">
          <% @characters.each do |char| %>
            <% if char.character_name != selected_char.character_name %>
              <div class="del-list">
                <% @open_secrets.each do |o_s| %>
                  <% if o_s.secret_id == s.id && char.pc_number == o_s.secret_unveil_to %>
                    <%= char.character_name %>
                    <div class="secret_unveil_box" data-id=<%= o_s.id %> data-token=<%= token %>>
                      <span data-unveil=<%= o_s.unveiled_id %>><%=o_s.unveiled.name%></span>
                    </div>
                  <% end %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
  </div>
</div>

app/views/secrets/_secret_form.html.erb
<div class="wrap-char-form" id="add-secret<%= num %>">
  <div class="form-background"></div>
  <div class="condition-feeling-form">
    <%= form_with model: @add_secret, url: room_secrets_path(room_token: token), method: :post do |f| %>
      <div class="form-title">
        秘密情報追加
      </div>
      <div class="form-contents">
        <% if flash[:error] && flash[:match] == "secret#{num}" %>
          <div class="error-msg">
            <ul>
              <li><%= "秘密を入力してください。" %></li>
            </ul>
          </div>
        <% end %>
        <div class="field">
          <label for="asltb-<%=num%>">秘密</label><span class="required-items"> 必須</span><br />
          <%= f.text_area :secret, placeholder: "秘密を入力", class: "long_text_box", id: "asltb-#{num}" %>

          <%= f.hidden_field :character_id, value: selected_char.id, id: "asci-#{num}" %>
          <%= f.hidden_field :pc_number, value: num, id: "aspn-#{num}" %>
          <%= f.hidden_field :secret_n, value: secret_n, id: "assn-#{num}" %>
        </div>
        <button class="add-btn">
          <%= f.submit "追加" %>
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/secrets/_show_secret.html.erb
<div class="status_over_frame", data-target="secret-info<%= num %>">
  <div class="status_name">
    秘密
  </div>
  <div class="secret_bubble", id="secret-info<%= num %>">
    <div class="char-upper-display">
      <%# 秘密追加モーダル表示 %>
      <% if @role == 200 %>
        <div>
          <button class="add-charinfo-btn modal_form", data-target="add-secret<%= num %>">秘密追加</button>
          <% secret_n = @secrets.where(character_id: selected_char.id).length + 1 %>
          <%= render "secrets/secret_form", num: num, token: @room.token, selected_char: selected_char, secret_n: secret_n %>
        </div>
      <% end %>
      <%# 秘密追加モーダル表示 %>

      <%# 秘密公開モーダル表示 %>
      <% @secrets.each do |s| %>
        <% if selected_char.id == s.character_id %>
          <%= render 'open_secrets/open_close', num: num, selected_char: selected_char, s: s %>
        <% end %>
      <% end %>
      <div id="secrets-<%=num%>"></div>
      <%# 秘密公開モーダル表示 %>
    </div>
  </div>
</div>

app/views/secrets/add_secret.js.erb
$('.wrap-char-form').fadeOut(200);
$("#secrets-<%=@secret[:num]%>").append(
  "<%= j(render 'open_secrets/open_close',
  num: @secret[:num],
  selected_char: @secret[:selected_char],
  s: @add_secret) %>"
);
$('.js-message-errors').empty();

$('.form-background').on('click', function() {
  $('.wrap-char-form').fadeOut(300);
  return false;
});
$('.edit-charinfo-btn').each(function() {
  $(this).on('click', function() {
    const target = $(this).data('target');
    const modal = document.getElementById(target);
    $(modal).fadeIn(300);
    return false;
  });
});

app/views/secrets/edit_secret.js.erb
$('.wrap-char-form').fadeOut(200);
$("#show-secret-<%=@pc_num%>-<%=@edit_secret.secret_n%>").html("<%= @edit_secret.secret %>");
$('.js-message-errors').empty();